### ISSUE TITLE
illumina bam 

### ISSUE THREAD

**Issue by aspitaleri** [wdecoster/nanocomp#25]
Please see my post here #13 about NanoComp on bam illumina.
Thanks

**Comment by wdecoster** [comment]
Hmm okay, so I once claimed it might work but Illumina bam files are definitely not the use case which I had in mind when writing NanoComp.
I'll have a look. It's always helpful if you include the log file, and especially important to include the full error message (which you didn't).

The critical part is:

```
concurrent.futures.process._RemoteTraceback: 
"""
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/wdecoster/miniconda3/envs/nanopack/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/wdecoster/miniconda3/envs/nanopack/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/wdecoster/miniconda3/envs/nanopack/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/wdecoster/miniconda3/envs/nanopack/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 221, in extract_from_bam
    for read in samfile.fetch(reference=chromosome, multiple_iterators=True)
  File "/home/wdecoster/miniconda3/envs/nanopack/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 222, in <listcomp>
    if not read.is_secondary]
  File "/home/wdecoster/miniconda3/envs/nanopack/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 233, in get_pID
    match = reduce(lambda x, y: x + y[1] if y[0] in (0, 7, 8) else x, read.cigartuples, 0)
TypeError: reduce() arg 2 must support iteration
"""
```

**Comment by aspitaleri** [comment]
okay thanks. the error message is included in the #13 post but indeed it is only the last part. do you still need it?

**Comment by wdecoster** [comment]
No, I reproduced the error and pasted the important part of the error message above. I'll have a fix for your issue online in a couple of minutes.

**Comment by wdecoster** [comment]
fixed in https://github.com/wdecoster/nanoget/commit/d8bfe094f8150fdb967339f2e468376fe89c6e4d
The updated code (nanoget v1.12.1) is available on PyPI. 
`pip install --upgrade nanoget`

**Comment by aspitaleri** [comment]
great! thanks a lot!

**Comment by aspitaleri** [comment]
Hi,
nanocomp works fine (I get the raw data so far it is enough for me). In the log I found this error related to "orca" software:
Note: When used on Linux, orca requires an X11 display server, but none was
detected. Please install Xvfb and configure plotly.py to run orca using Xvfb
as follows:

    >>> import plotly.io as pio
    >>> pio.orca.config.use_xvfb = True
    
You can save this configuration for use in future sessions as follows:
    >>> pio.orca.config.save() 
    
See https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml
for more info on Xvfb
Traceback (most recent call last):
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanoplotter/plot.py", line 60, in save_static
    pio.write_image(self.fig, self.path.replace('html', 'png'))
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/plotly/io/_orca.py", line 1705, in write_image
    fig, format=format, scale=scale, width=width, height=height, validate=validate
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/plotly/io/_orca.py", line 1482, in to_image
    ensure_server()
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/plotly/io/_orca.py", line 1344, in ensure_server
    validate_executable()
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/plotly/io/_orca.py", line 1139, in validate_executable
    raise ValueError(err_msg)
ValueError: 
The orca executable is required in order to export figures as static images,
but the executable that was found at '/home/aspitaleri/.conda/envs/nanopore/bin/orca'
does not seem to be a valid plotly orca executable. Please refer to the end of
this message for details on what went wrong.

If you haven't installed orca yet, you can do so using conda as follows:

    $ conda install -c plotly plotly-orca

Alternatively, see other installation methods in the orca project README at
https://github.com/plotly/orca.

After installation is complete, no further configuration should be needed.

If you have installed orca, then for some reason plotly.py was unable to
locate it. In this case, set the `plotly.io.orca.config.executable`
property to the full path of your orca executable. For example:

    >>> plotly.io.orca.config.executable = '/path/to/orca'

After updating this executable property, try the export operation again.
If it is successful then you may want to save this configuration so that it
will be applied automatically in future sessions. You can do this as follows:

    >>> plotly.io.orca.config.save()

If you're still having trouble, feel free to ask for help on the forums at
https://community.plot.ly/c/api/python

Here is the error that was returned by the command
    $ /home/aspitaleri/.conda/envs/nanopore/bin/orca --help

[Return code: 127]
/home/aspitaleri/.conda/envs/nanopore/lib/orca_app/orca: error while loading shared libraries: libXss.so.1: cannot open shared object file: No such file or directory

Note: When used on Linux, orca requires an X11 display server, but none was
detected. Please install Xvfb and configure plotly.py to run orca using Xvfb
as follows:

    >>> import plotly.io as pio
    >>> pio.orca.config.use_xvfb = True
    
You can save this configuration for use in future sessions as follows:
    >>> pio.orca.config.save() 
    
See https://www.x.org/releases/X11R7.6/doc/man/man1/Xvfb.1.xhtml
for more info on Xvfb

2020-03-02 16:04:57,921 Writing html report.
2020-03-02 16:04:57,945 range() arg 3 must not be zero
Traceback (most recent call last):
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 56, in main
    make_report(plots, settings["path"])
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 193, in make_report
    html_content.append(utils.stats2html(path + "NanoStats.txt"))
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanocomp/utils.py", line 37, in stats2html
    v = [chunks(i, num) for i in values]
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanocomp/utils.py", line 37, in <listcomp>
    v = [chunks(i, num) for i in values]
  File "/home/aspitaleri/.local/lib/python3.6/site-packages/nanocomp/utils.py", line 28, in chunks
    return([' '.join(values[i:i + chunksize]) for i in range(0, len(values), chunksize)])
ValueError: range() arg 3 must not be zero

installing orca and then rerun the analysis on the same dir will nanocomp restart from scratch?

Best

**Comment by wdecoster** [comment]
Orca is necessary to make static images of the dynamic html plots. You don't need it for NanoComp to function properly, it's optional.

Yes, if you install it you will have to start NanoComp again.
