### ISSUE TITLE
Error when using multiple threads for NanoComp 

### ISSUE THREAD

**Issue by callumparr** [wdecoster/nanocomp#41]
Getting the following error when using single or multi-threaded command. From some googling it might be some memory issue? 

Was running v1.34.1 for nanoplotter and v1.13.1 for NanoComp

2021-04-04 22:37:21,657 NanoComp 1.13.1 started with arguments Namespace(bam=['/analysisdata/rawseq/fastq/SHARED/000081/Interactome_project_ONT-CAGE/iPSC_rep1/run1/alignment/out_transcriptome.sorted.bam', '/home/scratch/callum/yonsei_iPSC_rep1/alignment/out_all_transcriptome.sorted.bam', '/home/scratch/callum/yonsei_iPSC_rep2/alignment/out_all_transcriptome.sorted.bam'], barcoded=False, colors=['orchid', 'seagreen', 'darkturquoise'], cram=None, dpi=300, fasta=None, fastq=None, feather=None, format='png', maxlength=None, minlength=None, names=['new_iPSC_rep1', 'old_iPSC_rep1', 'old_iPSC_rep2'], outdir='NanoComp/bam', path='NanoComp/bam/', pickle=None, plot='violin', prefix='', raw=False, readtype='1D', split_runs=False, store=False, summary=None, threads=4, title='new vs old ONT-CAGE libraries for iPSCs alignments', tsv_stats=False, ubam=None, verbose=True)
2021-04-04 22:37:21,659 Python version is: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38)  [GCC 7.3.0]
2021-04-04 22:37:21,660 Nanoplotter: valid output format png
2021-04-04 22:37:21,684 Nanoget: Starting to collect statistics from bam file /analysisdata/rawseq/fastq/SHARED/000081/Interactome_project_ONT-CAGE/iPSC_rep1/run1/alignment/out_transcriptome.sorted.bam.
2021-04-04 22:37:21,685 Nanoget: Starting to collect statistics from bam file /home/scratch/callum/yonsei_iPSC_rep1/alignment/out_all_transcriptome.sorted.bam.
2021-04-04 22:37:21,685 Nanoget: Starting to collect statistics from bam file /home/scratch/callum/yonsei_iPSC_rep2/alignment/out_all_transcriptome.sorted.bam.
2021-04-04 22:37:23,026 Nanoget: Bam file /analysisdata/rawseq/fastq/SHARED/000081/Interactome_project_ONT-CAGE/iPSC_rep1/run1/alignment/out_transcriptome.sorted.bam contains 109978197 mapped and 660906 unmapped reads.
2021-04-04 22:37:23,125 Nanoget: lots of contigs (>100), not running in separate processes
2021-04-04 22:37:23,406 Nanoget: Bam file /home/scratch/callum/yonsei_iPSC_rep2/alignment/out_all_transcriptome.sorted.bam contains 21206951 mapped and 168995 unmapped reads.
2021-04-04 22:37:23,415 Nanoget: Bam file /home/scratch/callum/yonsei_iPSC_rep1/alignment/out_all_transcriptome.sorted.bam contains 16433816 mapped and 145380 unmapped reads.
2021-04-04 22:37:23,506 Nanoget: lots of contigs (>100), not running in separate processes
2021-04-04 22:37:23,516 Nanoget: lots of contigs (>100), not running in separate processes
2021-04-04 22:54:28,001 Nanoget: bam /home/scratch/callum/yonsei_iPSC_rep1/alignment/out_all_transcriptome.sorted.bam contains 4928406 primary alignments.
2021-04-04 22:54:30,148 Reduced DataFrame memory usage from 734.975248336792Mb to 589.2723274230957Mb
2021-04-04 22:59:03,190 Nanoget: bam /home/scratch/callum/yonsei_iPSC_rep2/alignment/out_all_transcriptome.sorted.bam contains 6533981 primary alignments.
2021-04-04 22:59:05,893 Reduced DataFrame memory usage from 974.3895931243896Mb to 781.2196073532104Mb
Process Process-1:1:
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/callum/miniconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/home/callum/miniconda3/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/home/callum/miniconda3/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/callum/miniconda3/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
2021-04-04 23:41:21,890 A process in the process pool was terminated abruptly while the future was running or pending.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 165, in process_bam
    repeat(bam), unit, repeat(kwargs["keep_supp"]))
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 164, in <listcomp>
    data=[res for sublist in executor.map(extract_from_bam,
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 52, in main
    combine="track")
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 92, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 92, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 165, in process_bam
    repeat(bam), unit, repeat(kwargs["keep_supp"]))
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 164, in <listcomp>
    data=[res for sublist in executor.map(extract_from_bam,
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/callum/miniconda3/bin/NanoComp", line 8, in <module>
    sys.exit(main())
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 52, in main
    combine="track")
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 92, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/home/callum/miniconda3/lib/python3.6/site-packages/nanoget/nanoget.py", line 92, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/callum/miniconda3/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by wdecoster** [comment]
Ah, that's an annoying problem. So what happens is that the extraction of information from files happens in separate processes, and to pass back the data frame python uses serialization (in pickle format I believe). If the data to be passed back to the main thread is too large this is the error that you'll get. The number of threads you specified on the command line doesn't make a difference...

As ONT data becomes larger and larger this will happen more often, I'm afraid, and a large overhaul of the underlying code is planned. I don't have a great solution today, but a workaround is to use the [create_feather](https://github.com/wdecoster/nanoget/blob/master/scripts/create_feather.py) script with the `--huge` option. What this script will do is take your bam file (or other input for nanocomp/nanoplot) and save all read metrics in a binary `.feather` file, which you can then use later as input for NanoPlot/NanoComp... `--huge` ensures that the separate processes (the source of this error). It's a little inconvenient, but I hope this helps.

**Comment by callumparr** [comment]
Yeh this was LSK110 kit and got 5x as many reads as I am used to. It's quite something. That's good I will try this.

**Comment by LeilyR** [comment]
Hey,

I have tried create_feather to convert some large bam files into feather format. It does work perfectly fine for smaller bam files, but for those I can also use the bam formats. However, it fails for those that are lager than several Gs. When I use those feather files to run nanocomp I get this error:
`Traceback (most recent call last):
  File "/Users/leily/.conda/envs/ont/bin/NanoComp", line 10, in <module>
    sys.exit(main())
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 82, in main
    as_tsv=args.tsv_stats,
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanomath/nanomath.py", line 206, in write_stats
    write_stats_legacy(stats, names, output, datadfs)
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanomath/nanomath.py", line 247, in write_stats_legacy
    s.long_features_as_string()
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanomath/nanomath.py", line 64, in long_features_as_string
    self.top5_lengths = self.long_feature_as_string_top5(self._top5_lengths)
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanomath/nanomath.py", line 72, in long_feature_as_string_top5
    str(round(j, ndigits=1)) + "; " + k + ")" for i, j, k in field]
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanomath/nanomath.py", line 72, in <listcomp>
    str(round(j, ndigits=1)) + "; " + k + ")" for i, j, k in field]
TypeError: must be str, not float`

I wonder if you know where that error comes from nd could help me with, thanks!

**Comment by wdecoster** [comment]
For now I have no idea what is going on. Do you think it would be possible to share one of the files that causes this? I will try to follow up on this next week.

**Comment by LeilyR** [comment]
Hi Wouter, 

Thanks for the quick reply. I am afraid I cannot share the bam files, since they are from a password protected study. They are samples from this [study](https://www.nature.com/articles/s41467-020-15171-6).
Probably you can contact dbgap and ask them for a permission. If you just use SRR11142442, SRR11142436 you can already generate the error.

**Comment by wdecoster** [comment]
And what about the arrow file?

**Comment by LeilyR** [comment]
what is the array file? At the moment I am trying to test it using cram files with only 2 samples. It goes slow but not failed yet. Although it threw some warning/error messages but it is still running.
`
% NanoComp --cram *.cram -t 12 -o nanocomp_cram
[E::cram_index_load] Could not retrieve index file for 'SRR11142436.cram'
[E::cram_index_load] Could not retrieve index file for 'SRR11142442.cram'
[W::find_file_url] Failed to read reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Input/output error
[W::find_file_url] Failed to read reference "https://www.ebi.ac.uk/ena/cram/md5/1b22b98cdeb4a9304cb5d48026a85128": Input/output error`

**Comment by wdecoster** [comment]
I'm sorry for the confusion, the arrow file is the same as the feather file :)

**Comment by LeilyR** [comment]
just to let you know, it just failed now with the following error:

`Process Process-2:3:
Traceback (most recent call last):
  File "/Users/leily/.conda/envs/ont/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/Users/leily/.conda/envs/ont/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/Users/leily/.conda/envs/ont/lib/python3.6/multiprocessing/queues.py", line 347, in put
    self._writer.send_bytes(obj)
  File "/Users/leily/.conda/envs/ont/lib/python3.6/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/Users/leily/.conda/envs/ont/lib/python3.6/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 251, in process_cram
    extract_from_bam, repeat(cram), unit, repeat(kwargs["keep_supp"])
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanoget/extraction_functions.py", line 249, in <listcomp>
    res
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/leily/.conda/envs/ont/bin/NanoComp", line 10, in <module>
    sys.exit(main())
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanocomp/NanoComp.py", line 59, in main
    combine="track",
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanoget/nanoget.py", line 110, in get_input
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/Users/leily/.conda/envs/ont/lib/python3.6/site-packages/nanoget/nanoget.py", line 110, in <listcomp>
    dfs=[out for out in executor.map(extraction_function, files)],
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/leily/.conda/envs/ont/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
`
