### ISSUE TITLE
TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by PhDstuff** [wdecoster/nanocomp#6]
I have used NanoComp perfectly for fastq files however now I am trying to use NanoComp for bam files,
I have aligned my reads to a reference using Last-921 but when I run NanoComp I get this:

concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 297, in extract_from_bam
    for read in samfile.fetch(reference=chromosome, multiple_iterators=True)
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 298, in <listcomp>
    if not read.is_secondary]
  File "/home/samuel/.local/lib/python3.5/site-packages/nanomath/nanomath.py", line 53, in ave_qual
    return -10 * log(sum([10**(q / -10) for q in quals]) / len(quals), 10)
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 175, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in _process_chunk
    return [fn(*args) for args in chunk]
  File "/usr/lib/python3.5/concurrent/futures/process.py", line 153, in <listcomp>
    return [fn(*args) for args in chunk]
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 239, in process_bam
    data=[res for sublist in executor.map(extract_from_bam, params) for res in sublist],
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 239, in <listcomp>
    data=[res for sublist in executor.map(extract_from_bam, params) for res in sublist],
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: 'NoneType' object is not iterable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/samuel/.local/bin/NanoComp", line 11, in <module>
    sys.exit(main())
  File "/home/samuel/.local/lib/python3.5/site-packages/nanocomp/NanoComp.py", line 38, in main
    combine="track")
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 72, in get_input
    dfs=[out for out in executor.map(extration_function, files)],
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoget/nanoget.py", line 72, in <listcomp>
    dfs=[out for out in executor.map(extration_function, files)],
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
TypeError: 'NoneType' object is not iterable

The log file shows it is reading the bam files and creating a indexed bam.
Thanks in advance

**Comment by wdecoster** [comment]
Thanks for reporting this!
I haven't tested Last, I'll have to see what's different. Can you perhaps share a (small) bam file which reproduces this issue? If not, can you share the commands you used for alignment? 

Cheers, 
Wouter

**Comment by PhDstuff** [comment]
These are the commands I am using to produce the BAM file:

`lastdb indexed_name ref_genome.fa 
#create LAST maf file
lastal -q1 -r1 -a1 -b1 indexed_name DATA.fa | last-split  > DATA_LAST.maf
#convert maf to sam file
maf-convert sam DATA_LAST.maf > DATA.LAST.sam
#convert sam to bam file
samtools faidx ref_genome.fa
samtools view -bt ref_genome.fa.fai DATA_LAST.sam > DATA_LAST.bam

#sort the bam file
samtools sort DATA_LAST.bam DATA_LAST_sorted`

Thanks again
Samuel

**Comment by wdecoster** [comment]
Did I understand correctly that you're aligning a fasta file DATA.fa, and not a fastq file? In that case, no quality scores are present and the error you received is not surprising. I'll think of the best way to solve this.

**Comment by PhDstuff** [comment]
Yes I am just aligning a fasta file.
I did not know if NanoComp would try do all of the same comparisons as with the fastq file option.

**Comment by wdecoster** [comment]
Could you check if updating NanoComp (`pip install NanoComp -U`) solves your issue?

**Comment by PhDstuff** [comment]
Same error messages unfortunately

**Comment by wdecoster** [comment]
What do you get if you do `NanoComp -v`?

**Comment by PhDstuff** [comment]
NanoComp 0.12.2

**Comment by wdecoster** [comment]
Then you're not on the latest version, which is 0.12.3. Try `pip install NanoComp -U --no-cache-dir`.

**Comment by PhDstuff** [comment]
There was an issue with the package manager because I have both python 2.7 and python 3 sorry.
Re-ran and the error message now is: 

Traceback (most recent call last):
  File "/usr/local/bin/NanoComp", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/nanocomp/NanoComp.py", line 51, in main
    plots = make_plots(datadf, settings)
  File "/usr/local/lib/python3.5/dist-packages/nanocomp/NanoComp.py", line 215, in make_plots
    title=settings["title"])
  File "/home/samuel/.local/lib/python3.5/site-packages/nanoplotter/nanoplotter.py", line 478, in violin_or_box_plot
    linewidth=0)
  File "/home/samuel/.local/lib/python3.5/site-packages/seaborn/categorical.py", line 2364, in violinplot
    color, palette, saturation)
  File "/home/samuel/.local/lib/python3.5/site-packages/seaborn/categorical.py", line 557, in __init__
    self.establish_variables(x, y, hue, data, orient, order, hue_order)
  File "/home/samuel/.local/lib/python3.5/site-packages/seaborn/categorical.py", line 151, in establish_variables
    raise ValueError(err)
ValueError: Could not interpret input 'quals'

**Comment by wdecoster** [comment]
Uh-oh, sorry, that's an oversight on my side. Thought I was working on NanoPlot for a second, forgot to change a line in NanoComp. Could you try new version 0.12.4?

**Comment by PhDstuff** [comment]
Went perfectly, thanks Wouter

**Comment by wdecoster** [comment]
Good to hear. Please let me know if you encounter other issues or have suggestions/feature requests!
